site_name: Soil Erosion Watch â€“ RUSLE Documentation
site_description: GEE-based soil erosion assessment following Soil Erosion Watch philosophy
site_author: Tsitso Samuel Mafantiri
site_url: https://ocaes.github.io/soil-erosion-watch

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    scheme: default
    primary: green
    accent: light green

nav:
  - Home: index.md
  - Methods: methods.md
  - Data Sources: data.md
  - Model Factors: factors.md
  - Outputs: outputs.md
  - Limitations: limitations.md

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js